[package]
name = "mongodb-datafusion"
version = "0.1.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"

[dependencies]
arrow = "3"
async-trait = "0.1"
datafusion = "3"
futures = "0.3"
mongodb = "1"
mongodb-arrow = { path = "../mongodb-arrow" }
tokio = "0.2"
